@host = http://localhost:5086

GET {{host}}/health
Accept: application/json

###

POST {{host}}/api/github
Content-Type: application/json
Authorization: Bearer abc123
Accept: application/json

{
  "sample": "payload"
}

###
